### ISSUE TITLE
Model update for new data point ?

### ISSUE THREAD

**Issue by anujgupta82** [LIBOL/LIBSOL#2]
I am using python wrapper to use LIBSOL. I intialize the model as follows
from python.libsol_core import Model
m = Model(model_name = 'ogd', class_num = 2)
I get the data in online fashion
m.train('1st data point', 'svm', 1)

then I get the next data point and wish to further train the model on it, so should I do 
m.train('2nd data point', 'svm', 1) ?

**Comment by yuewu001** [comment]
yeah, you can continuously call m.train() for new training samples. One thing you may need to pay attention to is that the first parameter is a path to data file. Currently we are working on new wrappers so that you can pass a numpy array or scipy.csr_matrix as training data

**Comment by yuewu001** [comment]
in the new python interface, users can call m.fit() continuously for online learning. For C++ code, call m.Train().
