### ISSUE TITLE
Output of lsol_Test() not getting saved 

### ISSUE THREAD

**Issue by anujgupta82** [LIBOL/LIBSOL#3]
running the API from command line. 
I train a model using:
python python/libsol_train.py data/a1a

To save the output of running model over testdata, I run :
python python/libsol_test.py a1a.model data/a1a.t output_dump 

**However, I dont get any file "output_dump"**

**Comment by yuewu001** [comment]
by default, the current script save the predicted results to the cache folder. I have removed this setting  and save the output as it is. You can pull the latest code from the master branch and try again

**Comment by anujgupta82** [comment]
pulling the latest code worked. Thanks

When i look in the output file, it has following entries:

label	 predict	scores
-1	1	0.0724911
-1	-1	-1.03573
1	1	0.235168
1	-1	-0.216726
1	1	1.1232

I assume, first column is "**actual label**", 2nd column is "**predicted label**" and last column (score) is "**distance of the data point from the decision boundary**".
